version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devmatch-frontend
    restart: unless-stopped
    ports:
      - "3125:80"
    environment:
      - NODE_ENV=production

networks:
  devmatch-net:
    external: true
